[package]
name = "book"
version = "0.1.0"
authors = ["Dangelo Guanipa <dangelo.guanipa@witi.cl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
